<?xml version="1.0" ?>
<gamd>
    <temperature>300</temperature> <!-- unit.kelvin -->

    <system>
        <nonbonded-method>PME</nonbonded-method>
        <nonbonded-cutoff>0.9</nonbonded-cutoff> <!-- unit.nanometers -->
        <constraints>HBonds</constraints>
    </system>

    <barostat>
        <pressure>1.0</pressure> <!-- unit.bar -->
        <frequency>25</frequency>
    </barostat>
    
    <run-minimization>True</run-minimization>

    <integrator>
        <algorithm>langevin</algorithm>
        <boost-type>lower-dual</boost-type>
        <sigma0>
            <primary>6.0</primary> <!-- unit.kilocalories_per_mole -->
            <secondary>6.0</secondary> <!-- unit.kilocalories_per_mole -->
        </sigma0>
        <random-seed>0</random-seed>
        <dt>0.002</dt> <!-- unit.picoseconds -->
        <friction-coefficient>1.0</friction-coefficient> <!-- unit.picoseconds**-1 -->
        <number-of-steps> <!-- quick test -->
            <conventional-md-prep>2000</conventional-md-prep>
            <conventional-md>10000</conventional-md>
            <gamd-equilibration-prep>2000</gamd-equilibration-prep>
            <gamd-equilibration>20000</gamd-equilibration>
            <gamd-production>30000</gamd-production>
            <averaging-window-interval>50</averaging-window-interval>
        </number-of-steps>
    </integrator>

    <input-files>
      <xmlserializer>
        <coordinates>state.pdb</coordinates> <!-- pdb format -->
        <system>system.xml</system> <!-- xml format -->
      </xmlserializer>
    </input-files>

    <outputs>
        <directory>quick-output/lower-dual/</directory>
        <overwrite-output>True</overwrite-output>

        <reporting>
            <energy>
                <interval>500</interval>
            </energy>
            <coordinates>
                <file-type>NETCDF</file-type>
            </coordinates>
            <statistics>
                <interval>500</interval>
            </statistics>
        </reporting>
    </outputs>
</gamd>